HRMPhoneBook/Controllers/HRM_PHONEController.cs
using System;
using System.Data.Entity;
using System.Net;
using System.Web.Mvc;
using HRMPhoneBook.Data;
using HRMPhoneBook.ViewModels;
using System.DirectoryServices.AccountManagement;
using System.Configuration;
using System.Net.Mail;
using HRMPhoneBook.Cache;
using System.Security.Principal;

namespace HRMPhoneBook.Controllers
{
    public class HRM_PHONEController : Controller
    {
        private PhoneBookEntities db = new PhoneBookEntities();

        // GET: HRM_PHONE
        public ActionResult Index()
        {
            try
            {
                var repo = new PhoneBookRepository();
                var indexView = PhoneBookRepository.Index();

                ViewBag.SearchClicked = false;

                return View(indexView);
            }
            catch (Exception)
            {
                throw;
            }
        }

        [HttpPost]
        public ActionResult Search(PhoneIndexVM viewModel)
        {
            try { 
                if (ModelState.IsValid)
                {
                    var repo = new PhoneBookRepository();

                    var searcResults = PhoneBookRepository.Search(viewModel);

                    viewModel.SearchResults = searcResults;

                    viewModel.BusinessUnits = BusinessUnitsRepository.GetBusinessUnits();
                    viewModel.Streets = StreetsRepository.GetStreets();

                    ViewBag.SearchClicked = true;

                    return View(nameof(Index), viewModel);
                }

                viewModel.BusinessUnits = BusinessUnitsRepository.GetBusinessUnits();
                viewModel.Streets = StreetsRepository.GetStreets();

                ViewBag.SearchClicked = true;

                return View(nameof(Index), viewModel);
            }
            catch (Exception)
            {
                throw;
            }
        }

        // GET: HRM_PHONE/Details/5
        public ActionResult Details(int id)
        {
            try
            {
                if (id == 0)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }

                var repo = new PhoneBookRepository();
                var viewModel = PhoneBookRepository.Find(id);

                if (viewModel.SEQ_ID == 0)
                {
                    return HttpNotFound();
                }

                viewModel.BusinessUnits = BusinessUnitsRepository.GetBusinessUnits();
                viewModel.Streets = StreetsRepository.GetStreets();

                viewModel.PageMode = nameof(Edit);
                return View(viewModel);
            }
            catch (Exception)
            {
                throw;
            }
            }

        // GET: HRM_PHONE/Create
        public ActionResult Create()
        {
            try { 
                var viewModel = new HRMPhoneVM
                {
                    BusinessUnits = BusinessUnitsRepository.GetBusinessUnits(),
                    Streets = StreetsRepository.GetStreets(),

                    PageMode = nameof(Create)
                };
                return View(viewModel);
            }
            catch (Exception)
            {
                throw;
            }
        }

        // POST: HRM_PHONE/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "EMPL_ID,SEQ_ID,LAST_NME,FIRST_NME,TITLE_DSC,BUNIT_DSC,DIVISION_DSC,SECTION_DSC,LOCATION_DSC,WORK_PHN,FAX_PHN,CELL_PHN,PAGER_PHN,UPDATE_DTE,EMAIL_ID,BUSUNIT_CDE,STR_CODE,CIVIC_NBR,FLOOR")] HRM_PHONE hRM_PHONE)
        {
            try
            {
                var viewModel = new HRMPhoneVM
                {
                    EMPL_ID = hRM_PHONE.EMPL_ID,
                    SEQ_ID = hRM_PHONE.SEQ_ID,
                    LAST_NME = hRM_PHONE.LAST_NME,
                    FIRST_NME = hRM_PHONE.FIRST_NME,
                    TITLE_DSC = hRM_PHONE.TITLE_DSC,
                    BUNIT_DSC = hRM_PHONE.BUNIT_DSC,
                    DIVISION_DSC = hRM_PHONE.DIVISION_DSC,
                    SECTION_DSC = hRM_PHONE.SECTION_DSC,
                    LOCATION_DSC = hRM_PHONE.LOCATION_DSC,
                    WORK_PHN = hRM_PHONE.WORK_PHN,
                    FAX_PHN = hRM_PHONE.FAX_PHN,
                    CELL_PHN = hRM_PHONE.CELL_PHN,
                    PAGER_PHN = hRM_PHONE.PAGER_PHN,
                    UPDATE_DTE = hRM_PHONE.UPDATE_DTE,
                    EMAIL_ID = hRM_PHONE.EMAIL_ID,
                    BUSUNIT_CDE = hRM_PHONE.BUSUNIT_CDE,
                    STR_CODE = hRM_PHONE.STR_CODE,
                    CIVIC_NBR = hRM_PHONE.CIVIC_NBR,
                    FLOOR = hRM_PHONE.FLOOR,
                    BusinessUnits = BusinessUnitsRepository.GetBusinessUnits(),
                    Streets = StreetsRepository.GetStreets(),
                    PageMode = nameof(Create)
                };

                if (ModelState.IsValid)
                {
                    // if user is an phone book admin do the same 
                    // otherwise send them to a landing page
                    // to verify the create
                    if (IsPhoneBookAdmin())
                    {
                        hRM_PHONE.UPDATE_DTE = DateTime.Now;  //update the date 

                        db.HRM_PHONE.Add(hRM_PHONE);
                        db.SaveChanges();
                        //return RedirectToAction(nameof(Index));

                        return RedirectToAction(nameof(Edit), new { id = hRM_PHONE.SEQ_ID.ToString(), message = "Phone Record Created" });
                    }
                    else
                    {
                        viewModel.ActionMode = "CREATE";
                        return RedirectToAction(nameof(Review), viewModel);
                    }

                }

                return View(viewModel);
            }
            catch (Exception)
            {
                throw;
            }
}

        private bool IsPhoneBookAdmin()
        {
            try
            {
                using (PrincipalContext ctx = new PrincipalContext(ContextType.Domain))
                {
                    var userName = User.Identity.Name;
                    var isAdmin = false;

                    // find a user
                    var user = UserPrincipal.FindByIdentity(ctx, userName);

                    // find the group in question
                    var adminADGroup = ConfigurationManager.AppSettings["adminADGroup"];
                    var group = GroupPrincipal.FindByIdentity(ctx, adminADGroup);

                    if (user != null && group != null)
                    {
                        // get the authorization groups - those are the "roles" 
                        var groups = user.GetAuthorizationGroups();

                        //foreach (Principal principal in groups)
                        //{
                        //    // do something with the group (or role) in question
                        //}

                        // check if user is member of the Global AD group
                        if (user.IsMemberOf(group))
                        {
                            isAdmin = true;
                        }
                    }

                    if (!isAdmin)
                    {
                        //check if in local AD group
                        isAdmin = IsInGroup(userName, adminADGroup);
                    }


                    return isAdmin;
                }
            }
            catch (Exception)
            {
                throw;
            }
}

        static bool IsInGroup(string user, string group)
        {
            if (user.Contains("\\"))
            {
                user = user.Substring(user.IndexOf("\\") + 1);
            }

            using (WindowsIdentity identity = new WindowsIdentity(user))
            {
                var principal = new WindowsPrincipal(identity);
                return principal.IsInRole(group);
            }
        }

        // GET: HRM_PHONE/Edit/5
        public ActionResult Edit(int id, string message = null)
        {
            try
            {
                var repo = new PhoneBookRepository();
                var viewModel = PhoneBookRepository.Find(id);

                if (viewModel.SEQ_ID == 0)
                {
                    return HttpNotFound();
                }

                viewModel.BusinessUnits = BusinessUnitsRepository.GetBusinessUnits();
                viewModel.Streets = StreetsRepository.GetStreets();

                viewModel.PageMode = nameof(Edit);
                viewModel.PageMessage = message;
                return View(viewModel);
            }
            catch (Exception)
            {
                throw;
            }
        }

        // POST: HRM_PHONE/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "EMPL_ID,SEQ_ID,LAST_NME,FIRST_NME,TITLE_DSC,BUNIT_DSC,DIVISION_DSC,SECTION_DSC,LOCATION_DSC,WORK_PHN,FAX_PHN,CELL_PHN,PAGER_PHN,UPDATE_DTE,EMAIL_ID,BUSUNIT_CDE,STR_CODE,CIVIC_NBR,FLOOR")] HRM_PHONE hRM_PHONE)
        {
            try
            {
                var viewModel = new HRMPhoneVM
                {
                    EMPL_ID = hRM_PHONE.EMPL_ID,
                    SEQ_ID = hRM_PHONE.SEQ_ID,
                    LAST_NME = hRM_PHONE.LAST_NME,
                    FIRST_NME = hRM_PHONE.FIRST_NME,
                    TITLE_DSC = hRM_PHONE.TITLE_DSC,
                    BUNIT_DSC = hRM_PHONE.BUNIT_DSC,

HRMPhoneBook/Views/HRM_PHONE/Create.cshtml
@model HRMPhoneBook.ViewModels.HRMPhoneVM

@{
    ViewBag.Title = Model.PageMode + " Phone Record";
}
<div class="col-sm-12">
    <h2 style="margin-top:2em">
        @Model.PageMode Phone Record
    </h2>
    <hr />

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        @Html.ValidationSummary(true)

        @Html.Partial("_PhoneRecord", Model)

        <div style="margin-top:2em">
            <div style="text-align: right">

                @Html.ActionLink("Back to Search", "Index", "HRM_PHONE", null, new { @class = "btn btn-default", @style = "margin-right:10px" })
                <button type="submit" class="btn btn-primary">Save</button>
            </div>
        </div>
        <div style="margin-top:3em">
            <div style="text-align: right;">
                <h2>
                    @Model.PageMessage
                </h2>
            </div>
        </div>
    }
</div>
    @section Scripts {
        @Scripts.Render("~/bundles/jqueryval")
    }

HRMPhoneBook/Views/HRM_PHONE/Delete.cshtml
@model HRMPhoneBook.ViewModels.HRMPhoneVM

@{
    ViewBag.Title = "Delete Phone Record";
}

<div class="col-sm-12">
    <h2 style="margin-top:2em">Delete Phone Record</h2>
    <h3>Are you sure you want to delete this?</h3>
    <hr />

    @using (Html.BeginForm(null, null, FormMethod.Post, new { id = "frmDetails" }))
    {

            @Html.AntiForgeryToken()
            <div class="form-group">
                <div class="row">
                    <div class="col-sm-4">
                        @Html.LabelFor(model => model.LAST_NME, htmlAttributes: new { @class = "control-label" })

                        @Html.EditorFor(model => model.LAST_NME, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.LAST_NME, "", new { @class = "text-danger" })
                    </div>
                    <div class="col-sm-4">
                        @Html.LabelFor(model => model.FIRST_NME, htmlAttributes: new { @class = "control-label" })
                        @Html.EditorFor(model => model.FIRST_NME, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.FIRST_NME, "", new { @class = "text-danger" })
                    </div>
                    <div class="col-sm-4">
                        @Html.LabelFor(model => model.BUSUNIT_CDE, htmlAttributes: new { @class = "control-label" })
                        @Html.DropDownListFor(model => model.BUSUNIT_CDE, new SelectList(Model.BusinessUnits, "Value", "Text"), htmlAttributes: new { @class = "form-control", id = "BUSUNIT_CDE" })
                        @Html.ValidationMessageFor(model => model.BUSUNIT_CDE, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
            <div class="form-group">
                <div class="row">
                    <div class="col-sm-4">
                        @Html.LabelFor(model => model.TITLE_DSC, htmlAttributes: new { @class = "control-label" })
                        @Html.EditorFor(model => model.TITLE_DSC, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.TITLE_DSC, "", new { @class = "text-danger" })
                    </div>
                    <div class="col-sm-4">
                        @Html.LabelFor(model => model.SECTION_DSC, htmlAttributes: new { @class = "control-label" })

                        @Html.EditorFor(model => model.SECTION_DSC, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.SECTION_DSC, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
            <div class="form-group">
                <div class="row">
                    <div class="col-sm-4">
                        @Html.LabelFor(model => model.WORK_PHN, htmlAttributes: new { @class = "control-label" })

                        @Html.EditorFor(model => model.WORK_PHN, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.WORK_PHN, "", new { @class = "text-danger" })
                    </div>
                    <div class="col-sm-4">
                        @Html.LabelFor(model => model.CELL_PHN, htmlAttributes: new { @class = "control-label" })

                        @Html.EditorFor(model => model.CELL_PHN, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.CELL_PHN, "", new { @class = "text-danger" })
                    </div>
                    <div class="col-sm-4">
                        @Html.LabelFor(model => model.FAX_PHN, htmlAttributes: new { @class = "control-label" })
                        @Html.EditorFor(model => model.FAX_PHN, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.FAX_PHN, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
            <div class="form-group">
                <div class="row">
                    <div class="col-sm-4">
                        @Html.LabelFor(model => model.EMAIL_ID, htmlAttributes: new { @class = "control-label" })

                        @Html.EditorFor(model => model.EMAIL_ID, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.EMAIL_ID, "", new { @class = "text-danger" })
                    </div>
                    <div class="col-sm-4">
                        @Html.LabelFor(model => model.PAGER_PHN, htmlAttributes: new { @class = "control-label" })
                        @Html.EditorFor(model => model.PAGER_PHN, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.PAGER_PHN, "", new { @class = "text-danger" })
                    </div>
                    <div class="col-sm-4">
                        @Html.LabelFor(model => model.LOCATION_DSC, htmlAttributes: new { @class = "control-label" })
                        @Html.EditorFor(model => model.LOCATION_DSC, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.LOCATION_DSC, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
            <div class="form-group">
                <div class="row">
                    <div class="col-sm-4">
                        @Html.LabelFor(model => model.CIVIC_NBR, htmlAttributes: new { @class = "control-label" })
                        @Html.EditorFor(model => model.CIVIC_NBR, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.CIVIC_NBR, "", new { @class = "text-danger" })
                    </div>

                    <div class="col-sm-4">
                        @Html.LabelFor(model => model.STR_CODE, htmlAttributes: new { @class = "control-label" })
                        @Html.DropDownListFor(model => model.STR_CODE, new SelectList(Model.Streets, "Value", "Text"), htmlAttributes: new { @class = "form-control", id = "STR_CODE" })
                        @Html.ValidationMessageFor(model => model.STR_CODE, "", new { @class = "text-danger" })
                    </div>
                    <div class="col-sm-4">
                        @Html.LabelFor(model => model.FLOOR, htmlAttributes: new { @class = "control-label" })
                        @Html.EditorFor(model => model.FLOOR, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.FLOOR, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
            <div style="margin-top:2em">
                <div style="text-align: right">

                    @Html.ActionLink("Back to Search", "Index", "HRM_PHONE", null, new { @class = "btn btn-default", @style = "margin-right:10px" })
                    <button id="btnDelete" type="submit" class="btn btn-danger">Delete</button>
                </div>
            </div>
    }
    </div>
@section Scripts {
    <script type="text/javascript">
            $(document).ready(function () {
                $("#frmDetails :input").prop("readonly", true);
                $("#STR_CODE").prop("disabled", true);
                $("#BUSUNIT_CDE").prop("disabled", true);
            });
    </script>
}

HRMPhoneBook/Views/HRM_PHONE/Details.cshtml
@model HRMPhoneBook.ViewModels.HRMPhoneVM

@{
    ViewBag.Title = "Phone Record Details";
}

<div class="col-sm-12">
    <h2 style="margin-top:2em">Phone Record Details</h2>
    <hr />

    <form id="frmDetails">
        <div class="form-group">
            <div class="row">
                <div class="col-sm-4">
                    @Html.LabelFor(model => model.LAST_NME, htmlAttributes: new { @class = "control-label" })

                    @Html.EditorFor(model => model.LAST_NME, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.LAST_NME, "", new { @class = "text-danger" })
                </div>
                <div class="col-sm-4">
                    @Html.LabelFor(model => model.FIRST_NME, htmlAttributes: new { @class = "control-label" })
                    @Html.EditorFor(model => model.FIRST_NME, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.FIRST_NME, "", new { @class = "text-danger" })
                </div>
                <div class="col-sm-4">
                    @Html.LabelFor(model => model.BUSUNIT_CDE, htmlAttributes: new { @class = "control-label" })
                    @Html.DropDownListFor(model => model.BUSUNIT_CDE, new SelectList(Model.BusinessUnits, "Value", "Text"), htmlAttributes: new { @class = "form-control", id = "BUSUNIT_CDE" })
                    @Html.ValidationMessageFor(model => model.BUSUNIT_CDE, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>
        <div class="form-group">
            <div class="row">
                <div class="col-sm-4">
                    @Html.LabelFor(model => model.TITLE_DSC, htmlAttributes: new { @class = "control-label" })
                    @Html.EditorFor(model => model.TITLE_DSC, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.TITLE_DSC, "", new { @class = "text-danger" })
                </div>
                <div class="col-sm-4">
                    @Html.LabelFor(model => model.SECTION_DSC, htmlAttributes: new { @class = "control-label" })

                    @Html.EditorFor(model => model.SECTION_DSC, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.SECTION_DSC, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>
        <div class="form-group">
            <div class="row">
                <div class="col-sm-4">
                    @Html.LabelFor(model => model.WORK_PHN, htmlAttributes: new { @class = "control-label" })

                    @Html.EditorFor(model => model.WORK_PHN, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.WORK_PHN, "", new { @class = "text-danger" })
                </div>
                <div class="col-sm-4">
                    @Html.LabelFor(model => model.CELL_PHN, htmlAttributes: new { @class = "control-label" })

                    @Html.EditorFor(model => model.CELL_PHN, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.CELL_PHN, "", new { @class = "text-danger" })
                </div>
                <div class="col-sm-4">
                    @Html.LabelFor(model => model.FAX_PHN, htmlAttributes: new { @class = "control-label" })
                    @Html.EditorFor(model => model.FAX_PHN, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.FAX_PHN, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>
        <div class="form-group">
            <div class="row">
                <div class="col-sm-4">
                    @Html.LabelFor(model => model.EMAIL_ID, htmlAttributes: new { @class = "control-label" })

                    @Html.EditorFor(model => model.EMAIL_ID, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.EMAIL_ID, "", new { @class = "text-danger" })
                </div>
                <div class="col-sm-4">
                    @Html.LabelFor(model => model.PAGER_PHN, htmlAttributes: new { @class = "control-label" })
                    @Html.EditorFor(model => model.PAGER_PHN, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.PAGER_PHN, "", new { @class = "text-danger" })
                </div>
                <div class="col-sm-4">
                    @Html.LabelFor(model => model.LOCATION_DSC, htmlAttributes: new { @class = "control-label" })
                    @Html.EditorFor(model => model.LOCATION_DSC, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.LOCATION_DSC, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>
        <div class="form-group">
            <div class="row">
                <div class="col-sm-4">
                    @Html.LabelFor(model => model.CIVIC_NBR, htmlAttributes: new { @class = "control-label" })
                    @Html.EditorFor(model => model.CIVIC_NBR, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.CIVIC_NBR, "", new { @class = "text-danger" })
                </div>

                <div class="col-sm-4">
                    @Html.LabelFor(model => model.STR_CODE, htmlAttributes: new { @class = "control-label" })
                    @Html.DropDownListFor(model => model.STR_CODE, new SelectList(Model.Streets, "Value", "Text"), htmlAttributes: new { @class = "form-control", id = "STR_CODE" })
                    @Html.ValidationMessageFor(model => model.STR_CODE, "", new { @class = "text-danger" })
                </div>
                <div class="col-sm-4">
                    @Html.LabelFor(model => model.FLOOR, htmlAttributes: new { @class = "control-label" })
                    @Html.EditorFor(model => model.FLOOR, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.FLOOR, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>
    </form>

    <div style="margin-top:2em">
        <div style="text-align: right">

            @Html.ActionLink("Back to Search", "Index", "HRM_PHONE", null, new { @class = "btn btn-default", @style = "margin-right:10px" })
            @Html.ActionLink("Edit", "Edit", "HRM_PHONE", new { id = Model.SEQ_ID }, new { @class = "btn btn-primary" })
        </div>
    </div>
    </div>
    @section Scripts {
        <script type="text/javascript">
            $(document).ready(function () {
                $("#frmDetails :input").prop("disabled", true);
            });
        </script>
    }

HRMPhoneBook/Views/HRM_PHONE/Edit.cshtml
@model HRMPhoneBook.ViewModels.HRMPhoneVM

@{
    ViewBag.Title = Model.PageMode + " Phone Record";
}

<div class="col-sm-12">
    <h2 style="margin-top:2em">
        @Model.PageMode Phone Record
    </h2>
    <hr />

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        @Html.ValidationSummary(true)

        @Html.HiddenFor(model => model.SEQ_ID)
        @Html.Partial("_PhoneRecord", Model)

        <div style="margin-top:2em">
            <div style="text-align: right">

                @Html.ActionLink("Back to Search", "Index", "HRM_PHONE", null, new { @class = "btn btn-default", @style = "margin-right:10px" })
                <button type="submit" class="btn btn-primary">Save</button>
            </div>
        </div>
        <div style="margin-top:3em">
            <div style="text-align: right;">
                <h2>
                    @Model.PageMessage
                </h2>
            </div>
        </div>
    }
</div>
    @section Scripts {
        @Scripts.Render("~/bundles/jqueryval")
    }

HRMPhoneBook/Views/HRM_PHONE/Review.cshtml
@model HRMPhoneBook.ViewModels.HRMPhoneVM

@{
    ViewBag.Title = Model.PageMode + " Phone Record";
}

<div class="col-sm-12">
    <h2 style="margin-top:3em"></h2>


    @using (Html.BeginForm("SendEmail", "HRM_PHONE", FormMethod.Post, new { id = "frmReview" }))
    {
        @Html.AntiForgeryToken()

        @Html.ValidationSummary(true)

        @Html.HiddenFor(model => model.SEQ_ID)
        @Html.HiddenFor(model => model.ActionMode)
        @Html.Partial("_PhoneRecord", Model)

        <div style="text-align:right">
            <h3>
                This action will send an email to the Call Centre requesting an update, addition or removal of the employee on the previous screen.
            </h3>
            <h3>
                Are you sure you want to continue?
            </h3>
        </div>

        <div style="margin-top:2em">
            <div style="text-align: right">
                @Html.ActionLink("No", "Index", "HRM_PHONE", null, new { @class = "btn btn-default", id = "btnNo" })
                <button id="btnYes" type="submit" class="btn btn-primary" style="margin-left:10px">Yes</button>
            </div>
        </div>
    }
</div>
@section Scripts {
    <script type="text/javascript">
        $(document).ready(function () {
            $("#dvForm").hide();

            $("#btnYes").prop("disabled", false);
            $("#btnNo").prop("disabled", false);
        });
    </script>
    }

HRMPhoneBook/Views/HRM_PHONE/Sent.cshtml
@{
    ViewBag.Title = "Email Sent";
}


<div class="col-sm-12" style="margin-top:2em">
    <div style="text-align: right">
        @if (ViewBag.EmailSent)
        {
            <h2 style="margin-top:3em">Your message has been sent</h2>
        }
        else
        {
            <h2 style="margin-top:3em">Your message has NOT been sent</h2>
        }
    </div>
    <div style="margin-top:2em">
        <div style="text-align: right">
            @Html.ActionLink("Return to Search", "Index", "HRM_PHONE", null, new { @class = "btn btn-primary", id = "btnNo" })
        </div>
     </div>
</div>